// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UploadImage.Data;

#nullable disable

namespace UploadImage.Migrations
{
    [DbContext(typeof(UploadImageDbContext))]
    [Migration("20231118144850_Rumei2.0")]
    partial class Rumei20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UploadImage.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("double precision")
                        .HasColumnName("purchase_price");

                    b.HasKey("Id");

                    b.ToTable("tb_product");
                });

            modelBuilder.Entity("UploadImage.Models.ProductImages", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Image1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_1");

                    b.Property<string>("Image2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_2");

                    b.Property<string>("Image3")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_3");

                    b.Property<string>("Image4")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_4");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("tb_product_images");
                });

            modelBuilder.Entity("UploadImage.Models.ProductImages", b =>
                {
                    b.HasOne("UploadImage.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UploadImage.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
